framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: ~
    #http_method_override: true
    #esi: ~
    #fragments: ~
    session:
        handler_id: ~
    assets:
      version: '%assets.version%'
      version_format: '%%s?v=%%s'
    php_errors:
        log: true
