web:
    container_name: web
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./:/code
        - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

php:
    container_name: php
    build: ./.docker
    ports:
        - "9000:9000"
    volumes:
        - ./:/code
    links:
        - redis
        - postgres

redis:
    container_name: redis
    image: redis:latest

postgres:
    container_name: postgres
    image: postgres:latest
    ports:
        - "5432:5432"
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: root
        POSTGRES_PASSWORD:

mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
        - "1025:1025"
        - "8025:8025"
