services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
          $assets: '%assets%'

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

